version: "1.0.0"
services:
  api:
    build: ./data_processing
    volumes:
      - ./data_processing:/app/data_processing
    ports:
      - "8000:8000"
    stdin_open: true
    command: uvicorn src.main:app
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "7000:7000"
    depends_on:
      - api
    stdin_open: true
    tty: true
    command: mvn spring-boot:run
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/frontend/node_modules
    ports:
      - "4200:4200"
    # environment:
    #   - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    command: npm run start